---
- name: Create ticket with notes
  hosts: localhost
  gather_facts: no
  connection: local
  vars_files:
    snow_credentials.yml

  tasks:

  - name: Create a change request
    snow_record:
      state: present
      table: change_request
      username: "{{ sn_username }}"
      password: "{{ sn_password }}"
      instance: "{{ sn_instance }}"
      data:
        severity: "{{ sn_severity }}"
        priority: "{{ sn_priority }}"
        short_description: "{{ description }}"
    register: new_incident

  - debug: 
      var: new_incident.record.number